/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_main;

import App_Classes.AllergyCheckUp;
import app_dao.MysqlCon;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import openfoodfacts_API.MedicalEmergency;

/**
 *
 * @author Qasim.29
 */
public class CheckAllergyForm extends javax.swing.JPanel {

    /**
     * Creates new form CheckAllergyForm
     */
    ClientMedicalProfileJFrame jf;

    DefaultListModel listModel = new DefaultListModel();
    DefaultListModel listModel2 = new DefaultListModel();
    AllergyCheckUp a1;
    URI uri;

    public CheckAllergyForm(ClientMedicalProfileJFrame jf) {
        initComponents();
        txtEmail.setText(LoginForm.email);
        this.jf = jf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListallergy = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 600));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(71, 77, 122));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Check Food Allergies ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" User Email : ");

        txtEmail.setBackground(new java.awt.Color(71, 77, 122));
        txtEmail.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setDisabledTextColor(new java.awt.Color(71, 77, 122));
        txtEmail.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 59);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel1.setText("Enter Product Barcode :");
        add(jLabel1);
        jLabel1.setBounds(110, 110, 162, 20);
        add(txtBarcode);
        txtBarcode.setBounds(107, 131, 264, 39);

        btnCheck.setBackground(new java.awt.Color(71, 77, 122));
        btnCheck.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(255, 255, 255));
        btnCheck.setText("Check");
        btnCheck.setAutoscrolls(true);
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        add(btnCheck);
        btnCheck.setBounds(415, 129, 127, 39);

        jListallergy.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jListallergy.setSelectionBackground(new java.awt.Color(71, 77, 122));
        jScrollPane1.setViewportView(jListallergy);

        add(jScrollPane1);
        jScrollPane1.setBounds(107, 207, 435, 160);

        jLabel4.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel4.setText("Found Allergies :");
        add(jLabel4);
        jLabel4.setBounds(110, 190, 114, 20);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel5.setText("Our Recommendations :");
        add(jLabel5);
        jLabel5.setBounds(110, 390, 170, 20);

        jList2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jList2.setSelectionBackground(new java.awt.Color(71, 77, 122));
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2);
        jScrollPane2.setBounds(110, 410, 435, 180);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        listModel.clear();
        jListallergy.setModel(listModel);
        listModel2.clear();
        jList2.setModel(listModel2);
        try {
            a1 = new AllergyCheckUp((String) txtBarcode.getText().trim());
            
            if(txtBarcode.getText().trim().isEmpty()){
                throw new Exception();
            }
            //Integer.parseInt(();
            Long.parseLong((String)txtBarcode.getText().trim());
            a1.checkAllergy(MysqlCon.userAllergyRetrieve(LoginForm.email),a1.getBarcode());
            if (a1.isProductAllergic()) {
                JOptionPane.showMessageDialog(null, "Warning! Allergies found");

                for (String i : a1.getMatchedAllergies()) {
                    listModel.addElement(i);
                }
                jListallergy.setModel(listModel);

                for (String i : a1.emrgency(new MedicalEmergency())) {
                    uri = new URI(i);
                    listModel2.addElement(uri);
                }
                jList2.setModel(listModel2);
            } else {
                JOptionPane.showMessageDialog(null, "Hurray! NO, Allergies found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Barcode is invalid or either Allergies \n are not defined");
        }


    }//GEN-LAST:event_btnCheckActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(uri);
            } catch (Exception ex) {
            }
        } else {
        }
    }//GEN-LAST:event_jList2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<URI> jList2;
    private javax.swing.JList<String> jListallergy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables

}
