/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_main;

import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author Qasim.29
 */
public class ProfileUpdateForm extends javax.swing.JPanel {

    /**
     * Creates new form 
     */
    private ClientMedicalProfileJFrame jf;
    
    public ProfileUpdateForm(ClientMedicalProfileJFrame aThis) {
        initComponents();
        this.jf = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EditProfile = new javax.swing.JButton();
        EditProfile1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComGender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        jComBloodGroup = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(650, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 600));
        jPanel1.setLayout(null);

        EditProfile.setBackground(new java.awt.Color(71, 77, 122));
        EditProfile.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        EditProfile.setForeground(new java.awt.Color(255, 255, 255));
        EditProfile.setText("Update");
        EditProfile.setAutoscrolls(true);
        EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileActionPerformed(evt);
            }
        });
        jPanel1.add(EditProfile);
        EditProfile.setBounds(460, 450, 150, 46);

        EditProfile1.setBackground(new java.awt.Color(71, 77, 122));
        EditProfile1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        EditProfile1.setForeground(new java.awt.Color(255, 255, 255));
        EditProfile1.setText("Delete");
        EditProfile1.setAutoscrolls(true);
        EditProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfile1ActionPerformed(evt);
            }
        });
        jPanel1.add(EditProfile1);
        EditProfile1.setBounds(70, 450, 150, 46);

        jPanel2.setBackground(new java.awt.Color(71, 77, 122));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 710, 10);

        jComGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(jComGender);
        jComGender.setBounds(430, 300, 100, 20);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setText("Gender :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 300, 57, 19);

        txtHeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHeightFocusLost(evt);
            }
        });
        jPanel1.add(txtHeight);
        txtHeight.setBounds(360, 220, 253, 33);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel11.setText(" Height :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(360, 200, 57, 19);

        txtWeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWeightFocusLost(evt);
            }
        });
        jPanel1.add(txtWeight);
        txtWeight.setBounds(360, 150, 253, 33);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel12.setText("Weight :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(360, 130, 56, 19);

        txtAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAgeFocusLost(evt);
            }
        });
        jPanel1.add(txtAge);
        txtAge.setBounds(360, 80, 253, 33);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel10.setText("Age :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 60, 35, 19);
        jPanel1.add(txtPhoneNo);
        txtPhoneNo.setBounds(70, 220, 253, 33);

        jComBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A RhD positive (A+)", "A RhD negative (A-)", "B RhD positive (B+)", "B RhD negative (B-)", "O RhD positive (O+)", "O RhD negative (O-)", "AB RhD positive (AB+)", "AB RhD negative (AB-)" }));
        jComBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComBloodGroupActionPerformed(evt);
            }
        });
        jPanel1.add(jComBloodGroup);
        jComBloodGroup.setBounds(170, 280, 135, 20);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel8.setText("Blood Group :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 280, 94, 19);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel13.setText("Phone No. :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 200, 78, 19);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setText("Password :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 130, 72, 19);
        jPanel1.add(txtPassword);
        txtPassword.setBounds(70, 150, 253, 33);

        txtName.setToolTipText("enter you name");
        jPanel1.add(txtName);
        txtName.setBounds(70, 80, 253, 33);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setText("Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 60, 48, 19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfile1ActionPerformed

    private void EditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileActionPerformed
        
    }//GEN-LAST:event_EditProfileActionPerformed

    private void txtHeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHeightFocusLost
        if (jf.isDouble(txtHeight.getText()) != true) {
            txtHeight.setBorder(new LineBorder(Color.red, 1));
        } else {
            txtHeight.setBorder(new LineBorder(Color.black, 1));
        }
    }//GEN-LAST:event_txtHeightFocusLost

    private void txtWeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWeightFocusLost
        if (jf.isDouble(txtWeight.getText()) != true) {
            txtWeight.setBorder(new LineBorder(Color.red, 1));
        } else {
            txtWeight.setBorder(new LineBorder(Color.black, 1));
        }
    }//GEN-LAST:event_txtWeightFocusLost

    private void txtAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAgeFocusLost
        if (jf.isInt(txtAge.getText()) != true) {
            txtAge.setBorder(new LineBorder(Color.red, 1));
        } else
        txtAge.setBorder(new LineBorder(Color.black, 1));
    }//GEN-LAST:event_txtAgeFocusLost

    private void jComBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComBloodGroupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditProfile;
    private javax.swing.JButton EditProfile1;
    private javax.swing.JComboBox<String> jComBloodGroup;
    private javax.swing.JComboBox<String> jComGender;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
